backend:
  name: github
  repo: getdirty75/asymetrics
  branch: develop
  commit_messages:
    create: 'Content Manager creates new post {{collection}} “{{slug}}”'
    update: 'Content Manager update new post {{collection}} “{{slug}}”'
    delete: 'Content Manager delete new post {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titre --> affiché ds la home page et ds l'article", name: "title", widget: "string"}
      - {label: "Teaser --> affiché ds la home page et ds l'article", name: "teaser", widget: "text"}
      - {label: "Image --> affichée seulement ds la home page pas ds l'article", name: "featuredimage", widget: image}
      - {label: "Auteur", name: "author", widget: "select", options: ["MALONG", "LORD SANDWICH", "SUPER USER", "IZLAZ DA MAGNIFICIENT aka STICKY TAI", "THE UNKNOWN SOLDIER", "ASYMETRICS CREW", "FOLLOW THE WHITE RABBIT", "ENDLESS DAZE"]}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {
          label: "Categories",
          name: "categories",
          options: [{label: "Mixtapes / Playlists / Podcasts", value: "mixtapes"}, {label: "Knowledge / Wisdom / Rhythm", value: "knowledge"}, {label: "Artworks / Pictures / Design", value: "artworks"}],
          widget: "select"
        }
      - {label: "Tags --> #tags, #multiplesavecdesvirgules, #separatedComma, #toujoursavec1dièse", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Bloc de Paragraphes --> mettre une image et du texte alignés", name: "paragraphs", required: false, widget: object, fields: [{label: "Paragraphes", name: "blurbs", widget: "list", fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - {label: "Liste URL Liens internes --> liens vers des urls internes (articles du blog theasymetrics.com), affiché ds l'article, barre à droite", name: "insideLinks", required: false, widget: "list"}
      - {
          label: "Liens connexes --> liens vers des urls externes (autres sites), affiché ds l'article, barre à droite",
          name: "outsideLinks",
          required: false,
          widget: "object",
          fields: [{label: "liste", name: "outsideLinksList", widget: "list", fields: [{label: "texte", name: "text", widget: "string"}, {label: "lien", name: "link", widget: "string"}]}]
        }

