backend:
  name: github
  repo: getdirty75/asymetrics
  branch: develop
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titre --> affiché ds la home page et ds l'article", name: "title", widget: "string"}
      - {label: "Teaser --> affiché ds la home page et ds l'article", name: "teaser", widget: "text"}
      - {label: "Image --> affichée seulement ds la home page pas ds l'article", name: "featuredimage", widget: image}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Categories --> liste de mots séparés par 1 espace (pas de / ou autres)", name: "tags", widget: "list"}
      - {label: "Tags --> liste de mots séparés par 1 espace (pas de / ou autres)", name: "categories", widget: "list"}
      - {label: "Introduction --> texte de présentation, affiché en début d'article", name: "introduction", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Liste URL Liens internes --> liens vers des urls internes (articles du blog theasymetrics.com), affiché ds l'article, barre à droite", name: "insideLinks", widget: "list"}
      - {label: "Liste URL Liens connexes --> liens vers des urls externes (autres sites), affiché ds l'article, barre à droite", name: "outsideLinks", widget: "list"}

